#!/bin/bash

((!$#)) && echo "No branch name, command ignored!" && exit 1

git checkout -b "$(date +%Y_%m_%d)_$1" # create new branch
git push -u origin HEAD # push local branch to remote and create there
