#!/usr/bin/env python3
import fnmatch
import sys

def main():
    try:
        pattern = sys.argv[1]
    except IndexError:
        print('mygrep: No pattern supplied', file=sys.stderr)
        sys.exit(1)

    results = fnmatch.filter([_.rstrip('\n') for _ in sys.stdin.readlines()], pattern)
    for line in results:
        print(line)

if __name__ == '__main__':
    main()
